permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Erica Rios' Portfolio"
  description: |
    A collection of my best work, focusing on branding, layout work and illustration.
  font_url: "https://fonts.googleapis.com/css?family=Lora:400,700|Nunito:400,700"
  colors:
    background: "--color-secondary"
  rationales:
    typefaces.primary: |
      Lora was selected because it is a simple, easy to read font that compliments the header font, Nunito.
    typefaces.secondary: |
      Nunito was selected because of its casual yet professional look. The rounded corners help the website feel friendly and welcoming.
    colors.primary: |
      The primary colour blue was selected because it is a nice, versatile colour that can go well with lots of different accents. The navy blue was chosen to be an alternative to black.
    colours.secondary: |
      The frost colour was chosen to be for backgrounds of things like headers and cards, to stand out a bit from the white. It is also meant to be used on top of a black background.
