title: "Cards"
description: |
  Cards are used to display multiple different items on a page in a grid formation.

patterns:
  portfolio-card:
    title: "Portfolio Card"
    description: |
      The main card used to show all the thumbnails of my portfolio pieces.
